# -*- mode: ruby -*-
# vi: set ft=ruby :

# Globals.
ENV["LC_ALL"] = "en_ZA.UTF-8"

Vagrant.configure("2") do |config|

    # Box.
    config.vm.define "rabbitmq" do |d|
        d.vm.box = "generic/ubuntu2204"
        d.vm.box_version = "4.2.16"
        d.vm.hostname = "rabbitmq.hotrod.local"
        d.vm.network :private_network, \
          :ip => "192.168.235.22", \
          :mac => "000c2984db29", \
          :libvirt__always_destroy => true, \
          :libvirt__network_name => "hotrod", \
          :libvirt__netmask => "255.255.255.0", \
          :libvirt__host_ip => "192.168.235.1", \
          :libvirt__dhcp_enabled => false, \
          :libvirt__forward_mode => "veryisolated", \
          :libvirt__guest_ipv6 => false
        d.vm.synced_folder "upload", "/upload", owner: "root", group: "root"
        d.vm.post_up_message = "Ready."

        # Libvirt.
        config.vm.provider "libvirt" do |l|
            l.default_prefix = "hotrod_"
            l.memory = 2048
            l.cpus = 4
            l.graphics_type = "none"
            l.mgmt_attach = true
            l.management_network_name = "default"
            l.management_network_keep = true
        end

        # VMware.
        d.vm.provider "vmware_desktop" do |v|
            v.gui = false
            v.vmx["memsize"] = "2048"
            v.vmx["numvcpus"] = "2"
        end

        # Provision.
        d.vm.provision :shell, inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            mv /upload/10apt-cacher-ng.conf /etc/apt/apt.conf.d/10apt-cacher-ng
            #apt-get update
            #mkdir -m 0755 /etc/docker
            #mv /upload/daemon.json /etc/docker/daemon.json
            #apt-get -y install docker.io
            ##systemctl reload docker
            #docker pull 192.168.235.2:5000/nginx
        SHELL
    end
end
