# -*- mode: ruby -*-
# vi: set ft=ruby :

#BOX = "generic/ubuntu2204"
BOX = "panoptix/hotrod"
VERSION = "0.0.1"
DOMAIN = ".ephemeric.lan"
#ENV["PROXY"] = "false"

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.allow_hosts_modification = false
  config.vm.box = BOX
  config.vm.synced_folder "upload", "/vagrant", type: "rsync"
  config.vm.provider "libvirt" do |l|
      l.default_prefix = "ephemeric_"
      l.graphics_type = "none"
      l.management_network_name = "default"
      l.management_network_keep = true
  end
end

#load "config/robert"
load "config/test"
