---

# kubelet.service: EnvironmentFile=-/etc/default/crio
# crio.service: EnvironmentFile=-/etc/default/kublet
environment: |
  HTTP_PROXY="http://proxy.ephemeric.lan:3128"
  HTTPS_PROXY="http://proxy.ephemeric.lan:3128"
  NO_PROXY="registry.k8s.io,127.0.0.1,localhost,master-node,worker-node01,worker-node02,worker-node03,ephemeric.lan,172.16.,172.17.,172.16.1.0/16,172.17.1.0/18,192.168.235.,192.168.235.0/24"

network:
  # Worker IPs are incremented from control_ip.
  control_ip: 192.168.235.100
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 1
    cpu: 1
    memory: 2048
software:
  box: generic/ubuntu-22.04
  calico: 3.26.0
  metrics: 0.6.4
  dashboard: 2.7.0
  kubernetes: 1.27.2-00
  os: xUbuntu_22.04
