---

# kubelet.service: EnvironmentFile=-/etc/default/crio
# crio.service: EnvironmentFile=-/etc/default/kublet
environment: |
  HTTP_PROXY="http://proxy.ephemeric.lan:3128"
  HTTPS_PROXY="http://proxy.ephemeric.lan:3128"
  NO_PROXY="127.0.0.1,localhost,ephemeric.lan,172.16.,172.17.,172.16.1.0/16,172.17.1.0/18,192.168.235.,192.168.235.0/24"

network:
  # Worker IPs are incremented from control_ip.
  control_ip: 192.168.235.100
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
  domain: .ephemeric.lan
nodes:
  control:
    cpu: 4
    memory: 8192
  workers:
    count: 1
    cpu: 4
    memory: 8192
software:
  box: generic/ubuntu-22.04
  calico: 3.26.0
  metrics: 0.6.4
  dashboard: 2.7.0
  # `v1.27` for gpg curl, repo, `apt-get install kubeadm=1.27.5-1.1`.
  kubernetes: 1.28
  os: xUbuntu_22.04
