# -*- mode: ruby -*-
# vi: set ft=ruby s

NODES = [
    { :host => "rocky01", :box => "rockylinux/8", :ip => "192.168.56.10" , :cpu => 4 ,:ram => 2048 },
    { :host => "rocky02", :box => "rockylinux/8", :ip => "192.168.56.11" , :cpu => 4 ,:ram => 2048 },
    { :host => "rocky03", :box => "rockylinux/8", :ip => "192.168.56.12" , :cpu => 4 ,:ram => 2048 },
    { :host => "rocky04", :box => "rockylinux/8", :ip => "192.168.56.13" , :cpu => 4 ,:ram => 2048 },
]
DOMAIN = "ephemeric.lan"

Vagrant.configure("2") do |config|

    NODES.each do |member|

        config.vm.define member[:host] do |node|
        node.vm.box = member[:box]
        node.vm.network "private_network", ip: member[:ip], :netmask => "255.255.255.0"
        node.vm.hostname = "#{member[:host]}.#{DOMAIN}"
        node.vm.synced_folder "upload", "/vagrant", owner: "root", group: "root"
        node.vm.provision :shell, :path => "init-rocky.sh"
        node.vm.provider "libvirt" do |libvirt|
          libvirt.default_prefix = ""
           libvirt.memory = member[:ram].to_s
           libvirt.cpus = member[:cpu].to_s
           end

        #if member[:host] == "rocky01"
        #    node.vm.provision "shell", inline: <<-SHELL
        #    echo "slobwashere" >/tmp/slobwashere
        #    SHELL
        #    end

        end
    end
end
